version: '2'
services:
  corobo:
    image: meetmangukiya/corobo
    restart: always
    env_file: .secrets
    links:
      - answers
    environment:
      - ANSWER_END=http://answers:8000
      - BACKEND=Gitter
      - BOT_ADMINS=meetmangukiya
      - COBOT_PREFIX=corobo
      - IGNORE_USERNAMES=coala-bot co-robo
      - GH_ORG_NAME=coala
      - GL_ORG_NAME=coala
  answers:
    image: meetmangukiya/corobo-answers
    restart: always
