debus = false
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "coala.io"
watch = true
exposedbydefault = false

[acme]
email = "yuki@coala.io"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
dnsProvider = "cloudflare"
OnHostRule = true
