version: '2'
services:
  web:
    build: .
    restart: always
    expose:
      - 8000
    env_file: .secrets
    labels:
      - "traefik.backend=landing"
      - "traefik.docker.network=outside"
      - "traefik.frontend.rule=Host:webservices.coala.io"
      - "traefik.frontend.headers.STSSeconds=315569260"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.port=8000"
      - "traefik.enable=true"
networks:
  default:
    external:
      name: "outside"
